### ISSUE TITLE
DB : Create a Test Database in Google Cloud Big-Query (SQL

### ISSUE THREAD

**Issue by DharmikJoshi05** [DSC-McMaster-U/mac-FAQ-chatbot#10]
- Create a dataset - Name (Mac-FAQ-DATASET) or something similar
- After creating a dataset create a test-database table 
- Enter around 20 records with mutiple columns to test out the working of Cloud Functions

**Comment by Yunfei-Ma-McMaster** [comment]
Update: Extract FAQ Data from University Website

### Progress
- Successfully retrieved and parsed the one-page HTML content of the FAQ pages based on FAQ website structure`https://libanswers.mcmaster.ca/sitemap.xml`.
- Implemented a script to extract questions, answers, and related topics for a single-page
- Converted in-text hyperlinks in the answers to Markdown format, preserving their functionality while enabling easy storage in the database.
- Gathered multiple related topics when available, separating them with a comma for clear representation.

### Code Snippets
```python
# Extracting questions, answers, and related topics
question = soup.find('div', class_='s-la-faq-question').get_text()
answer = html_to_markdown(str(soup.find('div', class_='s-la-faq-answer')))
related_topics = [label.a.get_text(strip=True) for label in soup.find_all('span', class_='label-topic')]
label_texts = ', '.join(related_topics)
```

**Comment by allison-stack** [comment]
### **Update: Completed BigQuery tutorial (can be found in Google Cloud starter tutorials)**

- Learned basics of how to use BigQuery
- Queried a public dataset
- Experimented with queried dataset

**Next steps:**
- Continue getting familiar with BigQuery
- Follow more tutorials

**Comment by Yunfei-Ma-McMaster** [comment]
### Update: Local Test Database Creation with Schema
- Initialized a local test database incorporating a schema design.
- Populated with 4 sample FAQ entries for library queries.
- Data stored in CSV format for easy manipulation and storage.

### Schema Overview
Here's how the schema is structured:

```json
[
    {
        "name": "faq_id",
        "type": "STRING",
        "mode": "REQUIRED",
        "description": "The unique identifier for the FAQ"
    },
    {
        "name": "question",
        "type": "STRING",
        "mode": "REQUIRED",
        "description": "The extracted question"
    },
    {
        "name": "answer",
        "type": "STRING",
        "mode": "REQUIRED",
        "description": "The extracted answer in Markdown format"
    },
    {
        "name": "related_topics",
        "type": "STRING",
        "mode": "REPEATED",
        "description": "List of related topics associated with the FAQ"
    },
    {
        "name": "embeddings",
        "type": "FLOAT64",
        "mode": "REPEATED",
        "description": "Vector embeddings of the FAQ content for semantic search"
    }
]
```

### Current Challenge

Encountered an issue with the CSV text formatting and delimiters which is preventing the upload to BigQuery. This will be addressed in a subsequent update.

**Comment by Yunfei-Ma-McMaster** [comment]
## Update: BigQuery Upload Resolved

- **Resolved**: BigQuery upload issues.
- **Dataset**: Uploaded to `macfaqchatbot.mcmaster_library_faq.libans`.
- **Next Steps**:
  - Verification.
  - Begin backend integration.
  - Provide feedback on dataset structure and queries from other members.
---

**Comment by allison-stack** [comment]
### **Update: Uploaded new datasets (one consisting of university department information and another of university student information)**

- Found + uploaded datasets related to university stuff (university courses/IDs, student grades, student IDs, etc.) to the project
- Used basic SQL commands to query information from `test_department_information_table` and `test_student_information_table`

**Next steps:**
- Modify datasets/ create new datasets with McMaster info
- Seek feedback from teammates

**Comment by DharmikJoshi05** [comment]
Great Work !
