### ISSUE TITLE
DB: Explore possible open sources provided by McMaster University for FAQ

### ISSUE THREAD

**Issue by DharmikJoshi05** [DSC-McMaster-U/mac-FAQ-chatbot#11]
- Explore Sources provided by McMaster University for FAQ
- Decide a database strategy on how to store the FAQ information 
- Start creating a database design 
- Work on collecting more information about FAQ and store details in database.

**Comment by Yunfei-Ma-McMaster** [comment]
Sprint Goal 1:
- Explore Sources provided by McMaster University for FAQ

Competed Task:
- Explore Sources provided by McMaster University for FAQ in this [link](https://libanswers.mcmaster.ca/)

Risks and Challenges:
- Some answers contain only a reference link to another page (the chatbot may not query the direct answer)

Next Steps:
- Research possible draft answers along with database design

**Comment by DharmikJoshi05** [comment]
@Neaha-Bijo Whatever work you have done, Please mention it here.

**Comment by NeahaBijo** [comment]
More Sources:

- https://www.eng.mcmaster.ca/sept/bachelor-technology-frequently-asked-questions/
- https://www.eng.mcmaster.ca/engphys/any-questions/
- https://www.eng.mcmaster.ca/sept/bachelor-technology-frequently-asked-questions/admission-application/

Database Strategy:

- https://aws.amazon.com/what-is/data-strategy/#:~:text=A%20data%20strategy%20outlines%20an,needs%20it%20in%20your%20organization.
