### ISSUE TITLE
Getting Started with Dialogflow and creating sample Intents and Entities

### ISSUE THREAD

**Issue by DharmikJoshi05** [DSC-McMaster-U/mac-FAQ-chatbot#2]
- Use your Own Google Cloud Account for now for exploring Dialogflow. We get 600$ free credits and 12 months free trial on Dialogbox.
- Try creating few Agents and Training the Agent with sample questions.
- Create a few Intents and Entities and understand the Working
- Create a Google Document on the testing done and steps performed.

**Comment by DharmikJoshi05** [comment]
@kmehta2228  and @nivetha-kuruparan,
If you guys have any questions related to it. Please let me know. You can comment in this issue or ask me on the discord chat.

Here are few sample videos to get you guys started.
https://www.youtube.com/watch?v=qEJjlB002Tk&ab_channel=ParwizForogh
https://www.youtube.com/results?search_query=dialogflow

**Comment by DharmikJoshi05** [comment]
Here is the link to shared Google Drive, where you can upload the document once completed:
https://drive.google.com/drive/u/2/folders/1CkWa4xQbwYCMLho45I4EEq_GhTXybgUv

**Comment by nivetha-kuruparan** [comment]
Update: I created a Google Cloud Account and played around with Dialogflow Essential Interface by watching a few YouTube tutorials

**Quick summary:**
- Intents: represent user intentions or goals. Map what the user says to the corresponding action or response
- Entities: basically parameters within user messages that are needed to fulfil intents. Help extract specific information from user input
     - Already has predefined entities (date, number, etc.) 
     - Can make custom entities as well 
- Context: carries information between user interactions, making conversations more dynamic and contextually aware
     - Help connect intents together 
- Fulfillment: refers to the backend logic or code that processes user input and generates responses. It can be integrated with webhooks or inline code

**Resources** (will update)

- https://cloud.google.com/dialogflow/docs/

**Comment by DharmikJoshi05** [comment]
Ready to be closed.
