### ISSUE TITLE
Familiarise with Google Cloud Functions

### ISSUE THREAD

**Issue by DharmikJoshi05** [DSC-McMaster-U/mac-FAQ-chatbot#4]
- Go through the Documentation and understanding of Google Cloud Functions

**Comment by Stella-Gu** [comment]
https://cloud.google.com/functions?hl=en#section-4 
Went through the first two quickstart modules in the documentation section. Haven’t tested out the functions yet.

**Comment by DaniBoi2** [comment]
worked through a couple of modules, Tested out HTTP functions, will be looking at event driven functions next. 
https://cloud.google.com/functions/docs/writing/write-event-driven-functions

**Comment by Daniyal-Arif** [comment]
Tested out HTTP functions, will be looking at event-driven functions next. 
https://cloud.google.com/functions/docs/writing/write-event-driven-functions

**Comment by Stella-Gu** [comment]
Done
- Created and deployed a 2nd gen function (console) https://cloud.google.com/functions/docs/console-quickstart 

To Do
- Create and deploy a 2nd gen function (gcloud) https://cloud.google.com/functions/docs/create-deploy-gcloud
