### ISSUE TITLE
Database Structure and Approaches

### ISSUE THREAD

**Issue by DharmikJoshi05** [DSC-McMaster-U/mac-FAQ-chatbot#6]
- Which approach to use - SQL or NOSQL?
- Create a sample or initial Database Diagram (you can use draw.io)
- Sample data and dataset for our chatbot. (links to mcmaster FAQ page and similar links)

**Comment by Yunfei-Ma-McMaster** [comment]
Some readings and possible resources
- **SQL** or NoSQL
    - [SQL vs. NoSQL Databases: What’s the Difference?](https://www.ibm.com/blog/sql-vs-nosql/)
    - [SQL vs NoSQL vs BigQuery](https://zaidahmedsoomro.medium.com/sql-vs-nosql-vs-bigquery-b63e5565dd08)
- Database Diagram
    - [How to Create a Database Diagram](https://www.edrawsoft.com/how-to-create-database-diagram.html)
- Sample data
    - [McMaster LibAnswers Frequently Asked Questions (FAQ)](https://libanswers.mcmaster.ca/)

**Comment by NeahaBijo** [comment]
* Which approach to use - SQL or NOSQL?
    * Google BigQuery uses column based relational databases not NoSQL databases
    * If the data is structured SQL is the best choice.
    * SQL supports JOIN and Complex queries and follows the ACID properties
    * https://www.ibm.com/blog/sql-vs-nosql/
    * https://zaidahmedsoomro.medium.com/sql-vs-nosql-vs-bigquery-b63e5565dd08

* Sample data
    * https://libanswers.mcmaster.ca/
    * https://ug.degroote.mcmaster.ca/resources/current-student-resources/
    * https://www.eng.mcmaster.ca/future-students/future-undergraduate-students/faqs/
    * https://www.eng.mcmaster.ca/programs/engineering-i/faqs/
    * https://www.eng.mcmaster.ca/programs/academic-advising/faqs/
    * https://www.eng.mcmaster.ca/co-op-career/co-op-program/faqs/
    * https://cse.mcmaster.ca/graduate-studies/frequently-asked-questions/
    * https://housing.mcmaster.ca/residence-faq/
    * https://bhsc.healthsci.mcmaster.ca/faqs/
    * https://ugme.healthsci.mcmaster.ca/about-us/faq/
    * https://sas.mcmaster.ca/accommodations/frequently-asked-questions/
    * https://sees.mcmaster.ca/undergraduate/faq/
    * https://midwiferyundergrad.mcmaster.ca/frequently-asked-questions/
    * https://office365.mcmaster.ca/office-365-3/o365-support/faqs-for-office-365/
    * https://www.eng.mcmaster.ca/civil/questions/

**Comment by DharmikJoshi05** [comment]
Good work !
