### ISSUE TITLE
BACK-END : Use the webhook and process the data provided by the Dialogflow

### ISSUE THREAD

**Issue by DharmikJoshi05** [DSC-McMaster-U/mac-FAQ-chatbot#9]
- Using Python Code, and already created Cloud-Functions
- Write a logic to access the data provided by Dialogflow using the webhook 
- Process the data and Write logic for fetching corresponding details from Big Query

**Comment by Daniyal-Arif** [comment]
Created a temporary agent on Diagflow so I could use its response to parse the data. 
Currently working on creating webhook (doing all this on a separate project, once I figure it out, I will integrate it to macfaqchatbot)

Resources used
1. https://cloud.google.com/dialogflow/cx/docs/quick/webhook
2. https://medium.com/google-cloud/maximizing-your-chatbot-experience-a-step-by-step-guide-to-adding-dynamic-responses-with-af5741b3defb

**Comment by DharmikJoshi05** [comment]
- @kmehta2228  Please create a webhook in dialogflow and share it here once done.
- @Daniyal-Arif to complete testing the webhook and dialogflow agent here.

**Comment by kmehta2228** [comment]
- I have explored Webhook and Inline editor powered by Cloud Function in Dialogflow Es. And I think we can work with Inline Editor.

**Comment by DharmikJoshi05** [comment]
Completed!
